### ISSUE TITLE
Windows UWP - Widevine

### ISSUE THREAD

**Issue by Munnday** [aussieaddons/repo#69]
With UWP, Widevine downloads to %LOCALAPPDATA%\Packages\XBMCFoundation.Kodi_4n2hpmxwrvr6p\LocalCache\Roaming\Kodi\cdm

It appears when Aussie addons is attempting to load the library its looking in %appdata%Roaming\Kodi\cdm\

Also, ssd_wv is trying to download from https://github.com/xbmc-catchuptv-au/repo-binary/raw/master/Krypton/windows-x86-ssd_wv-9af2121.dll which dosn't exist

**Comment by andybotting** [comment]
Hi David,
I've just bought an Xbox recently for working on this stuff. Did you manage to make this work with the UWP version on Windows? Did it actually load the libraries?

cheers,
Andy

**Comment by Munnday** [comment]
The libraries appeared to download, well the windevine did, but ssd_vw dosn't due to 404

> NOTICE: [DRMHELPER 1.1.0] - Downloading https://github.com/xbmc-catchuptv-au/repo-binary/raw/master/Krypton/windows-x86-ssd_wv-9af2121.dll
> 
> NOTICE: [DRMHELPER 1.1.0] - Error retrieving https://github.com/xbmc-catchuptv-au/repo-binary/raw/master/Krypton/windows-x86-ssd_wv-9af2121.dll

> ERROR: AddOnLog: InputStream Adaptive: Unable to load widevine shared library (C:\Users\user\AppData\Roaming\Kodi\cdm\widevinecdm.dll)
> 
> ERROR: AddOnLog: InputStream Adaptive: OpenDRMSystem failed

widevine library did download though, to the UWP roaming path of %LOCALAPPDATA%\Packages\XBMCFoundation.Kodi_4n2hpmxwrvr6p\LocalCache\Roaming\Kodi\cdm\widevinecdm.dll

**Comment by andybotting** [comment]
I'm keen to get this fixed up if possible. I think I've got the 404 bit sorted.

You can grab the ssd_wv DLL from https://github.com/aussieaddons/repo-binary/raw/master/Krypton/windows-x86-libssd_wv-9af2121.dll

If you put them all in the right place, does it work?

**Comment by Munnday** [comment]
Renaming to ssd_vw.dll and putting the in cdm folder with widevinecdm.dll?  If so, then it appears to be happy, dosn't attempt to download it and no errors in the log regarding.

widevinecdm.dll not loading due to the location error

> 20:28:21.161 T:3184   ERROR: AddOnLog: InputStream Adaptive: Unable to load widevine shared library (C:\Users\user\AppData\Roaming\Kodi\cdm\widevinecdm.dll)
20:28:21.161 T:3184   ERROR: AddOnLog: InputStream Adaptive: OpenDRMSystem failed

**Comment by andybotting** [comment]
OK that's good news.

It appears that the CDM path is set within Inputstream.adaptive, and not set by us at all. It defaults to 'special://home/cdm' and is configured in the inputstream.adaptive add-on settings. 

I wonder if this is bug for them.

@glennguy is my man for Windows stuff. He might be able to help out here.

**Comment by Munnday** [comment]
Ahh yes I see, it looks like  "special://xbmc" points to the correct location

> special://xbmc/ is mapped to: C:\Program Files\WindowsApps\XBMCFoundation.Kodi_17.9.601.0_x86__4n2hpmxwrvr6p

> special://home/ is mapped to: C:\Users\user\AppData\Roaming\Kodi\

**Comment by Munnday** [comment]
I see.  It looks like Kodi dosn't have a special:// path for the roaming path of the UWP app. hmmm!
