### ISSUE TITLE
Script.module dependencies not loaded with iview add-on - fresh kodi install

### ISSUE THREAD

**Issue by MajicDesigns** [aussieaddons/repo#72]
Kodi fresh install on Raspberry Pi. The only other add-on installed was YouTube.

On installing the iView add-on from zip file, a message that the add-on failed to install because script.module.aussieaddonscommon was missing. After much search found that, installed and got failure message due to script.module.drmhelper not installed. Found that, installed and then on to failure script.module.pycaption not installed. After this one, iview finally installed with no errors and it is now working.

Am I supposed to supposed to work this hard to install iview this or was there an easier way that I missed?

**Comment by andybotting** [comment]
Install the repo zip file, rather than the zip files of the individual add-ons. All the dependencies will be resolved and fetched from the repository ;)

**Comment by andybotting** [comment]
Try this:
http://aussieaddons.com/installation/

**Comment by MajicDesigns** [comment]
Well, that was a much better experience. Thanks for your help. 

How I got to my earlier installation point was by searching for "Kodi iView". The first link is to your repo with a readme file that had the line:
**First step is the grab the repo ZIP file.**
linking to "https://github.com/aussieaddons/repo/tree/master/plugin.video.abc_iview", which led me down the path I went. You may want to review that link, as I think linking to the same link in the video would make more sense.

**Comment by glennguy** [comment]
Thanks @MajicDesigns for the find!
