### ISSUE TITLE
Video Error

### ISSUE THREAD

**Issue by modano182** [aussieaddons/repo#73]
AFL Video v1.9.1 ERROR

play.py (47) - AussieAddonsException: Failed to obtain a secure token: this is not a recognized embed code.
Check your subscription is valid.

I have a Telstra Live pass free from Telstra. Was working fine last night but now not working.

**Comment by modano182** [comment]
I tried remove stored login token and re-logging in but keep getting the same error.

Logged an error report #4073

**Comment by Contopaxi** [comment]
Just did the same steps as you but no luck.

**Comment by modano182** [comment]
Right in time for the Power match :( haha

**Comment by Contopaxi** [comment]
Hoping they fix it for the Hawthorn game later.

Not sure what the issue would be if it worked last night.

**Comment by glennguy** [comment]
Looking into it now :)

**Comment by Contopaxi** [comment]
Thanks!

**Comment by modano182** [comment]
Thanks Glenn!

**Comment by modano182** [comment]
Seems to be working again...not sure if this was just a random intermittent issue...

**Comment by glennguy** [comment]
Yeah it's a bit interesting... I found another issue to fix anyway so not all bad!

**Comment by will4543** [comment]
I was getting the same error, deleted the addon and reinstalled and it was all good but could've just been an intermittent thing. The video is smoother than ever for me :) thankyou!
