### ISSUE TITLE
Live Feed - AFL.TV or Live games are failing - No error

### ISSUE THREAD

**Issue by steven3499** [aussieaddons/repo#74]
Within the Live Matches menu, if I select [Live now] kodi attempts to run the stream and then stops. This is the same for AFL.TV

Kodi is installed on a windows 10 pc
AFL addon. 1.9.2
Kodi 18.1

Debugging Error Reports 4234 and 4235

Thanks in advance. Steven

**Comment by andybotting** [comment]
I think you've installed Kodi from the Windows Store, which won't work for live streams which now require DRM.

See http://aussieaddons.com/drm/ for more info, but basically you'll need to download Kodi and install Kodi directly, not from the Windows Store.

**Comment by steven3499** [comment]
Andrew. 

Thanks for the quick reply. 

I did as you suggested. Removed the Kodi windows store Version from the pc. Downloaded and install Kodi from the main installation and download site.

A few moments ago I finished installing your afl addon And got the same result trying to access AFL.TV. I’m not too concerned though and will try it again when live matches recommence on Thursday.

Thank you for the advice. Steven


<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by steven3499** [comment]
>Andrew.  ...

@steven3499 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by steven3499** [comment]
Andrew - thank you. Streamed Collingwood v Richmond last night.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by andybotting** [comment]
Glad to hear it!
