### ISSUE TITLE
No videos working

### ISSUE THREAD

**Issue by creaper76** [aussieaddons/repo#76]
Debug log 4453

I can't get anything to work since going to kodi 18.1 and afl 1.9.2 or nrl app. I have a feeling it has something to do with inputstream.adaptive but I can"t seem to find it to install it.

**Comment by creaper76** [comment]
Ok debug log 4454 I did a fresh install of kodi 18.1 and all 1.9.2 on my shield and still getting the same fault.

**Comment by glennguy** [comment]
Hey @creaper76

Your log is saying that it can't resolve ooyala.com - lots of adblockers blacklist this address. 

Do you have any adblockers installed on your shield or router, or any smart DNS or VPN set up?

**Comment by creaper76** [comment]
Thanks glennguy. I'm not running an adblocker so not sure why player.ooyala.com would be blocked. I checked on a browser and I can get to the page ok. I installed kodi and afl1.9.2 on my phone and it works great. I hot spotted the shield to my phone and I'm still getting the ooyala error so I don't know what is going on there, pulling my hair out now lol

**Comment by glennguy** [comment]
Are you running a custom version of Kodi? The log has the android package name as `com.aussiesports.fork`

**Comment by glennguy** [comment]
nvm, can see that was from the first log not the second.
How about if you install the afl app on the shield? If that's failing then at least we can narrow it down to something on the Shield.
