### ISSUE TITLE
AFL Live streams disappear

### ISSUE THREAD

**Issue by steven3499** [aussieaddons/repo#80]
Hi.

Within Kodi version 18.1 I have the afl addon version 2.0.4 installed. Earlier in the week navigated to the AFL Live Stream and tested the live stream by playing some of AFL Live program. Last night, thought I might watch a little of the Richmond Carlton game, but within Live stream, all of the upcoming games were listed, but Richmond V Carlton was not, at game time.

Tonight the same thing happened for the Collingwood V Bulldogs game. 10 minutes before the game began, the game was listed within live stream, but 10 minutes later, at game time, it was no longer listed.

Installation is on an Imac computer.

**Comment by glennguy** [comment]
Hi @steven3499 thanks for the detailed explanation

To be clear there are 3 types of entries in the Live Matches section - current live streams, upcoming AFL games and upcoming AFLW games. The upcoming matches are there for convenience but do not represent the actual streams. They're programmed to no longer display once the game has started - it will mimic the how the games are displayed in the official app's 'Matches' section. Once the match stops being grey in there it will also no longer be in Kodi's upcoming matches.

The live streams in the addon come from a different source to the upcoming matches, and there was an issue last night which caused none of the live matches to show but that has been fixed as far as I can tell with 2.0.4 - see aussieaddons/plugin.video.afl-video#2641

Are you sure that you've updated successfully to 2.0.4 on your imac?

If the match still isn't there please submit a debug log for us?

Steps are:
* Enable debug logging within Kodi - Settings -> System -> Logging -> toggle 'Enable debug logging'
* Restart Kodi
* Go into the AFL addon and into the live matches
* Now open the addon's settings, go to the debugging tab and chose 'Send error report'
* Post back here with the issue number

Thanks

Glenn

**Comment by glennguy** [comment]
btw working ok atm here on 2.0.4:
![afl kodi](https://user-images.githubusercontent.com/11909320/77153079-3e1b6e80-6aed-11ea-827b-054cb1a67ba7.jpg)

**Comment by steven3499** [comment]
Hi Glenn

Issue number is 5830
Kodi version 18.1 Leia
AFL Video Addon 2.0.4
![Screen Shot 2020-03-20 at 10 22 12 pm](https://user-images.githubusercontent.com/48910508/77163282-79bc3580-6af9-11ea-9e2a-cf6b1be5a9d2.png)

I will check again tomorrow for Essendon V Fremantle game tomorrow at 1.10 QLD time.
![Screen Shot 2020-03-20 at 10 19 07 pm](https://user-images.githubusercontent.com/48910508/77163441-d1f33780-6af9-11ea-95af-0d682dcf90b4.png)

Like I mentioned - 10 minutes before the game the listing exists, but not immediately following the start of the game. I'll let you know tomorrow.

Thanks for the really fast reply.

**Comment by glennguy** [comment]
Thanks for the issue report. It looks though like it was run after the game had finished? - in which case we wouldn't have a live stream anyway...

If it happens again with today's game can you try the add-on on another device and see if the same issue is there?

**Comment by steven3499** [comment]
Hey Glenn

Missed the earlier match, (busy dealing with children) but Adelaide V Sydney is now fine. 

Closing the ticket, and thanks for your help.

Steven

**Comment by glennguy** [comment]
Awesome that's great to hear, maybe just an intermittent issue on their end....
