### ISSUE TITLE
Input Stream Adaptive Not Compatible With This Version of Kodi

### ISSUE THREAD

**Issue by thomfam** [aussieaddons/repo#94]
I am having a look at the 21.0 beta version of Kodi and installing my favorite addons.  Your Cricket Live addon however is unplayable on Kodi 20.2 as I am being told "Input Stream Adaptive Not Compatible With This Version of Kodi". Hopefully there can be a fix for this.

**Comment by glennguy** [comment]
I'm not sure if the cricket addon even works anymore.
However regarding inputstream.adaptive - if you've just done a copy paste of your add-ons folder then this may be why you get that error and you should upgrade the add-on to a version that is compatible.
For Windows/Mac/Android it will be in the Kodi repo.
On Linux platforms you have to build it or install separately from a package manager. LibreELEC and CoreELEC have their own repos in Kodi that this add-on should be in.

**Comment by thomfam** [comment]
Cricket Live addon works great.  You've helped me previously Glenguy with Cricket Live.  I appreciate you getting back to me.  Will do an update and see how it goes. Yes I did do a copy paste. Just did a clean install into Kodinerds 21 and working perfectly.
Close

**Comment by thomfam** [comment]
All good, keep up the good work and keep Cricket Live working. Thanks.
